POST http://localhost:4000/api/orders
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "joedohn@gmail.com",
    "totalPaid": 106.96,
    "order": [
        {
            "item": "5f2dd8234f965009404da056",
            "quantity": 2
        }
    ]
}